import type { Listing } from "./types";

const negotiable = {
  fa: "قیمت توافقی",
  en: "Price on request",
  ar: "السعر عند الطلب",
  ru: "Цена по запросу",
};

export const listings: Listing[] = [
  {
    slug: "forest-villa-namak-abrud",
    featured: true,
    images: ["/images/villa-forest.jpg", "/images/interior.jpg", "/images/nature.jpg"],
    title: {
      fa: "ویلای جنگلی لوکس، محدوده نمک‌آبرود",
      en: "Luxury Forest Villa, Namak Abrud area",
      ar: "فيلا فاخرة في الغابة، منطقة نمك آبرود",
      ru: "Люксовая лесная вилла, район Намак-Абруд",
    },
    type: {
      fa: "ویلای جنگلی",
      en: "Forest villa",
      ar: "فيلا في الغابة",
      ru: "Лесная вилла",
    },
    areaSqm: 850,
    location: {
      fa: "مازندران، محدوده نمک‌آبرود",
      en: "Mazandaran, Namak Abrud area",
      ar: "مازندران، منطقة نمك آبرود",
      ru: "Мазандаран, район Намак-Абруд",
    },
    deedStatus: {
      fa: "سند تک‌برگ",
      en: "Single-page deed",
      ar: "سند مفرد",
      ru: "Единый документ на право собственности",
    },
    potential: {
      fa: "مناسب سکونت و سرمایه‌گذاری",
      en: "Ideal for living and investment",
      ar: "مناسبة للسكن والاستثمار",
      ru: "Идеально для проживания и инвестиций",
    },
    price: negotiable,
    description: {
      fa: "ویلای لوکس با معماری مدرن در دل جنگل، مشرف به فضای سبز بکر، با متریال درجه‌یک و حریم کامل.",
      en: "A modern-architecture luxury villa in the heart of the forest, overlooking pristine greenery, with premium materials and full privacy.",
      ar: "فيلا فاخرة بتصميم عصري في قلب الغابة، تطل على مساحات خضراء بكر، بمواد فاخرة وخصوصية تامة.",
      ru: "Роскошная вилла современной архитектуры в сердце леса, с видом на нетронутую зелень, из премиальных материалов и с полной приватностью.",
    },
  },
  {
    slug: "buildable-urban-land-sari",
    featured: true,
    images: ["/images/land.jpg", "/images/nature.jpg"],
    title: {
      fa: "زمین شهری با قابلیت ساخت، ساری",
      en: "Buildable Urban Land, Sari",
      ar: "أرض حضرية قابلة للبناء، ساري",
      ru: "Городской участок под застройку, Сари",
    },
    type: {
      fa: "زمین شهری",
      en: "Urban land",
      ar: "أرض حضرية",
      ru: "Городской участок",
    },
    areaSqm: 1200,
    location: {
      fa: "ساری، موقعیت مرکزی",
      en: "Sari, central location",
      ar: "ساري، موقع مركزي",
      ru: "Сари, центральная локация",
    },
    deedStatus: {
      fa: "سند ملکی، دارای پروانه",
      en: "Freehold deed, permit issued",
      ar: "سند ملكية، مع رخصة",
      ru: "Право собственности, разрешение получено",
    },
    potential: {
      fa: "مناسب مشارکت در ساخت",
      en: "Suitable for construction partnership",
      ar: "مناسبة للمشاركة في البناء",
      ru: "Подходит для партнёрства в строительстве",
    },
    price: negotiable,
    description: {
      fa: "زمین شهری با موقعیت ممتاز و دسترسی عالی، آماده‌ی مشارکت در ساخت با سازندگان معتبر.",
      en: "Prime urban land with excellent access, ready for construction partnership with reputable developers.",
      ar: "أرض حضرية بموقع مميز وسهولة وصول، جاهزة للمشاركة في البناء مع مطورين موثوقين.",
      ru: "Городской участок в отличной локации с прекрасной доступностью, готов к партнёрству в строительстве.",
    },
  },
  {
    slug: "caspian-coastal-land",
    featured: true,
    images: ["/images/coastal.jpg", "/images/nature.jpg"],
    title: {
      fa: "زمین ساحلی خزر، موقعیت اول ساحل",
      en: "Caspian Coastal Land, first-row beach",
      ar: "أرض ساحلية على بحر قزوين، الصف الأول",
      ru: "Прибрежный участок Каспия, первая линия",
    },
    type: {
      fa: "زمین ساحلی",
      en: "Coastal land",
      ar: "أرض ساحلية",
      ru: "Прибрежный участок",
    },
    areaSqm: 2000,
    location: {
      fa: "مازندران، نوار ساحلی",
      en: "Mazandaran, coastal strip",
      ar: "مازندران، الشريط الساحلي",
      ru: "Мазандаран, прибрежная полоса",
    },
    deedStatus: {
      fa: "در حال بررسی وضعیت سند",
      en: "Deed status under review",
      ar: "حالة السند قيد المراجعة",
      ru: "Статус документа уточняется",
    },
    potential: {
      fa: "پتانسیل بالای سرمایه‌گذاری",
      en: "High investment potential",
      ar: "إمكانات استثمارية عالية",
      ru: "Высокий инвестиционный потенциал",
    },
    price: negotiable,
    description: {
      fa: "زمین ساحلی کم‌نظیر با دسترسی مستقیم به دریا، مناسب پروژه‌های اقامتی و توریستی.",
      en: "A rare beachfront plot with direct sea access, ideal for residential and tourism projects.",
      ar: "قطعة أرض ساحلية نادرة بوصول مباشر إلى البحر، مثالية للمشاريع السكنية والسياحية.",
      ru: "Редкий участок на берегу с прямым выходом к морю, идеален для жилых и туристических проектов.",
    },
  },
  {
    slug: "industrial-unit-sari",
    featured: false,
    images: ["/images/industrial.jpg"],
    title: {
      fa: "واحد صنعتی فعال، شهرک صنعتی ساری",
      en: "Active Industrial Unit, Sari industrial zone",
      ar: "وحدة صناعية فاعلة، المنطقة الصناعية بساري",
      ru: "Действующий промышленный объект, промзона Сари",
    },
    type: {
      fa: "املاک صنعتی",
      en: "Industrial",
      ar: "عقار صناعي",
      ru: "Промышленный объект",
    },
    areaSqm: 5000,
    location: {
      fa: "ساری، شهرک صنعتی",
      en: "Sari, industrial zone",
      ar: "ساري، المنطقة الصناعية",
      ru: "Сари, промышленная зона",
    },
    deedStatus: {
      fa: "سند و مجوزهای بهره‌برداری",
      en: "Deed and operating permits",
      ar: "سند وتصاريح تشغيل",
      ru: "Документ и разрешения на эксплуатацию",
    },
    potential: {
      fa: "مناسب تولید و سرمایه‌گذاری صنعتی",
      en: "Suited to manufacturing and industrial investment",
      ar: "مناسبة للتصنيع والاستثمار الصناعي",
      ru: "Подходит для производства и промышленных инвестиций",
    },
    price: negotiable,
    description: {
      fa: "واحد صنعتی با زیرساخت کامل، سالن تولید، انبار و مجوزهای معتبر، آماده‌ی بهره‌برداری.",
      en: "A fully-serviced industrial unit with production hall, warehouse and valid permits, ready to operate.",
      ar: "وحدة صناعية بمرافق كاملة وصالة إنتاج ومستودع وتصاريح سارية، جاهزة للتشغيل.",
      ru: "Полностью оснащённый промышленный объект с цехом, складом и действующими разрешениями.",
    },
  },
  {
    slug: "commercial-tower-unit",
    featured: false,
    images: ["/images/commercial.jpg", "/images/interior.jpg"],
    title: {
      fa: "واحد تجاری-اداری، مرکز ساری",
      en: "Commercial-Office Unit, downtown Sari",
      ar: "وحدة تجارية-مكتبية، وسط ساري",
      ru: "Коммерческо-офисное помещение, центр Сари",
    },
    type: {
      fa: "املاک تجاری و اداری",
      en: "Commercial & office",
      ar: "تجاري ومكتبي",
      ru: "Коммерция и офис",
    },
    areaSqm: 320,
    location: {
      fa: "ساری، خیابان اصلی تجاری",
      en: "Sari, main commercial street",
      ar: "ساري، الشارع التجاري الرئيسي",
      ru: "Сари, главная торговая улица",
    },
    deedStatus: {
      fa: "سند تجاری",
      en: "Commercial deed",
      ar: "سند تجاري",
      ru: "Коммерческий документ",
    },
    potential: {
      fa: "بازدهی اجاره‌ای مطمئن",
      en: "Dependable rental yield",
      ar: "عائد إيجاري موثوق",
      ru: "Стабильная арендная доходность",
    },
    price: negotiable,
    description: {
      fa: "واحد تجاری-اداری در بهترین موقعیت شهر با بازدهی اجاره‌ای پایدار و قابلیت رشد ارزش.",
      en: "A commercial-office unit in the city's best location with steady rental yield and value growth.",
      ar: "وحدة تجارية-مكتبية في أفضل موقع بالمدينة بعائد إيجاري مستقر ونمو في القيمة.",
      ru: "Коммерческо-офисное помещение в лучшей локации города со стабильной доходностью и ростом стоимости.",
    },
  },
  {
    slug: "agricultural-garden-land",
    featured: false,
    images: ["/images/nature.jpg", "/images/land.jpg"],
    title: {
      fa: "باغ و زمین کشاورزی، حومه ساری",
      en: "Garden & Agricultural Land, Sari outskirts",
      ar: "بستان وأرض زراعية، ضواحي ساري",
      ru: "Сад и сельхозземля, окрестности Сари",
    },
    type: {
      fa: "باغ و زمین کشاورزی",
      en: "Garden & agricultural land",
      ar: "بستان وأرض زراعية",
      ru: "Сад и сельхозземля",
    },
    areaSqm: 6000,
    location: {
      fa: "حومه ساری، منطقه سرسبز",
      en: "Sari outskirts, green area",
      ar: "ضواحي ساري، منطقة خضراء",
      ru: "Окрестности Сари, зелёная зона",
    },
    deedStatus: {
      fa: "سند و آب و درختان مثمر",
      en: "Deed, water and fruit trees",
      ar: "سند ومياه وأشجار مثمرة",
      ru: "Документ, вода и плодовые деревья",
    },
    potential: {
      fa: "مناسب اقامتگاه و کشاورزی",
      en: "Suited to retreat and farming",
      ar: "مناسبة للاستراحة والزراعة",
      ru: "Подходит для загородного дома и хозяйства",
    },
    price: negotiable,
    description: {
      fa: "باغ سرسبز با درختان مثمر و منبع آب، مناسب ساخت اقامتگاه شخصی و کشاورزی.",
      en: "A lush garden with fruit trees and a water source, ideal for a private retreat and farming.",
      ar: "بستان أخضر بأشجار مثمرة ومصدر مياه، مثالي لبناء استراحة خاصة والزراعة.",
      ru: "Зелёный сад с плодовыми деревьями и источником воды, идеален для дома и хозяйства.",
    },
  },
];
